// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/lrayt/sparrow/example/Internal/database"
	"github.com/lrayt/sparrow/example/app/dao"
	"github.com/lrayt/sparrow/example/app/handler"
	"github.com/lrayt/sparrow/example/app/service"
)

// Injectors from wire.go:

func InitExampleServer() (*ExampleServer, func(), error) {
	dbManager := database.NewDBManager()
	orderInfoDao := dao.NewOrderInfoDao(dbManager)
	orderInfoService := service.NewOrderInfoService(orderInfoDao)
	httpHandler := handler.NewHttpHandler(orderInfoService)
	exampleServer, err := NewExampleServer(httpHandler, dbManager)
	if err != nil {
		return nil, nil, err
	}
	return exampleServer, func() {
	}, nil
}

// wire.go:

var InternalProvider = wire.NewSet(database.NewDBManager)

// DaoProvider 数据库操作
var DaoProvider = wire.NewSet(dao.NewOrderInfoDao)

// ServiceProvider 业务处理
var ServiceProvider = wire.NewSet(service.NewOrderInfoService)

// HandlerProvider 获取参数
var HandlerProvider = wire.NewSet(handler.NewHttpHandler)
